
text={("!"|"\'" |"!"|"\""|"#" |"$" |"%"|"&"|"("|")"|	"*"|"+"|","|"-"|"}"|"."|ASCII_ALPHANUMERIC)+}
chrs={SOI ~"chs"~ EOI}

field = { text? ~ (empty_entity | entity)* ~text? }

entity = { "<" ~ PUSH(ASCII_ALPHANUMERIC+) ~ ">" ~ field  ~ "</" ~ POP ~ ">" }
empty_entity = { ("<" ~ PUSH(ASCII_ALPHANUMERIC+) ~ ">" ~ "</" ~ POP ~ ">") }
xml = {SOI ~(empty_entity| entity | "")~ EOI }



WHITESPACE = _{ " " | NEWLINE }
